obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.1


inflation_radius: 0.5
cost_scaling_factor: 10.0

transform_tolerance: 1.0  # wcześniej miałeś 0.5 lub 0.8

map_type: costmap
obstacle_layer:
  observation_sources: scan
  scan:
    data_type: LaserScan
    sensor_frame: base_scan
    topic: /scan
    marking: true
    clearing: true

