obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.1

inflation_radius: 0.1
transform_tolerance: 0.8
cost_scaling_factor: 1
update_frequency: 5.0
publish_frequency: 2.0


obstacle_layer:
  observation_sources: scan
  scan:
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
