obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.2
inflation_radius: 0.4
transform_tolerance: 0.5

#plugins:
#  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
#  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
#  - {name: restriction_layer, type: "costmap_2d::StaticLayer"}  # Twoja warstwa ograniczająca
