obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.07

map_type: costmap

obstacle_layer:
  observation_sources: scan
  scan:
    data_type: LaserScan
    sensor_frame: base_scan
    topic: /scan
    marking: true
    clearing: true

plugins:
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - { name: virtual_layer, type: "virtual_costmap_layer::VirtualLayer" }
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

virtual_layer:
  enabled: true
  zone_topics:     ["/navigation_zone"]
  obstacle_topics: ["/virtual_obstacles"]
  forms: []