global_frame: map
robot_base_frame: base_footprint

update_frequency: 6.0
publish_frequency: 6.0
transform_tolerance: 0.6


static_map: false
rolling_window: true
width: 15.0
height: 15.0
resolution: 0.05

plugins:
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - { name: virtual_layer, type: "virtual_costmap_layer::VirtualLayer" }
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}


virtual_layer:
  enabled: true
  zone_topics:     ["/navigation_zone"]
  obstacle_topics: ["/virtual_obstacles"]
  forms: []