global_frame: map
robot_base_frame: base_footprint

update_frequency: 10.0
publish_frequency: 10.0
transform_tolerance: 0.8

static_map: false
rolling_window: true
width: 15.0
height: 15.0
resolution: 0.01

plugins:
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
