global_frame: map
robot_base_frame: base_footprint

update_frequency: 6.0
publish_frequency: 6.0
transform_tolerance: 0.6

inflation_radius: 0.8
cost_scaling_factor: 20.0

static_map: false
rolling_window: true
width: 15.0
height: 15.0
resolution: 0.02
