global_frame: map
robot_base_frame: odom

update_frequency: 2.0
publish_frequency: 1.0
transform_tolerance: 0.5

static_map: false
rolling_window: true
resolution: 0.05
#plugins:
#  - {name: static_layer, type: "costmap_2d::StaticLayer"}
#  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
#  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
#  - {name: restriction_layer, type: "costmap_2d::StaticLayer"}  # dodatkowa warstwa
