global_frame: odom
robot_base_frame: base_footprint

update_frequency: 6.0
publish_frequency: 6.0
transform_tolerance: 0.6

inflation_radius: 0.2
cost_scaling_factor: 7.0

static_map: false
rolling_window: true
width: 6.0
height: 6.0
resolution: 0.01

