
global_frame: odom
robot_base_frame: base_footprint
update_frequency: 6.0
publish_frequency: 6.0
transform_tolerance: 0.3
inflation_radius: 0.15
cost_scaling_factor: 2.0
static_map: false
rolling_window: true
width: 6.0
height: 6.0
resolution: 0.05


plugins:
  - {name: static_layer,    type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
  - { name: virtual_layer, type: "virtual_costmap_layer::VirtualLayer" }
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

virtual_layer:
  enabled: true
  zone_topics:     ["/navigation_zone"]
  obstacle_topics: ["/virtual_obstacles"]
  forms: []