shutdown_costmaps: false         # Nie wyłączamy costmap w trybie bezczynności – robot cały czas "widzi" otoczenie

controller_frequency: 20.0       # Częstotliwość sterowania – wystarczająco płynnie, bez dużego obciążenia CPU
planner_frequency: 1.0           # Globalny plan odświeżany raz na sekundę – idealne do wolnych, ciasnych przestrzeni

transform_tolerance: 0.8         # Tolerancja TF – większa, aby unikać błędów przy drobnych opóźnieniach

planner_patience: 7.0            # Czekamy max 7s na wygenerowanie planu – potem recovery
controller_patience: 5.0         # Czekamy max 5s na komendę sterowania – potem recovery

conservative_reset_dist: 1.0     # Czyścimy tylko najbliższy obszar (1m) – bez naruszania ścian czy mebli

oscillation_timeout: 10.0        # Po 10s oscylacji bez postępu – recovery
oscillation_distance: 0.1        # Minimalny wymagany postęp – 10 cm

recovery_behavior_enabled: true  # Automatyczne próby wycofania/obrotu przy problemach
clearing_rotation_allowed: true  # Pozwalamy na obrót w miejscu w celu czyszczenia przeszkód

# Te parametry możesz dostroić dalej:
# - Zmniejsz controller_frequency do 10.0 jeśli masz ograniczone CPU
# - Zwiększ oscillation_timeout jeśli robot porusza się bardzo powoli