TebLocalPlannerROS:
  odom_topic: odom
  map_frame: odom

  max_vel_x: 0.75
  max_vel_x_backwards: 0.75
  max_vel_theta: 0.125
  acc_lim_x: 0.5
  acc_lim_theta: 0.2

  footprint_model:
    type: "circular"
    radius: 0.2

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05
  free_goal_vel: false

  # Trajectory
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.03
  max_global_plan_lookahead_dist: 3.0
  global_plan_viapoint_sep: 0.5

  # Obstacles
  min_obstacle_dist: 0.2
  inflation_dist: 0.4
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false

  # Via-points and others
  enable_homotopy_class_planning: false
  enable_multithreading: true
