TebLocalPlannerROS:
  odom_topic: "/odometry/filtered"

  max_vel_x: 0.30
  max_vel_x_backwards: 0.20
  max_vel_theta: 0.125
  acc_lim_x: 0.5
  acc_lim_theta: 0.2

  footprint_model:
    type: "circular"
    radius: 0.2

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.3
  free_goal_vel: false

  teb_autosize: true
  dt_ref: 0.2
  dt_hysteresis: 0.03
  max_global_plan_lookahead_dist: 0.4
  global_plan_viapoint_sep: 0.5
  via_points_ordered: true


  min_obstacle_dist: 0.25
  inflation_dist: 0.5
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false

  enable_homotopy_class_planning: false
  enable_multithreading: true

  weight_viapoint: 1.0
  weight_obstacle: 50.0
  weight_dynamic_obstacle: 10.0
  weight_inflation: 0.2
  weight_kinematics_forward_drive: 1.0
  weight_kinematics_turning_radius: 1.0

  prune_global_plan: true
