frequency: 6
sensor_timeout: 0.2
two_d_mode: true

# Odometry
odom0: /low_level_odom
odom0_config: [true, true, false, false, false, true,
               false, false, false, false, false, false,
               false, false, false]
odom0_differential: false
odom0_relative: true

# SLAM pose correction
pose0: /poseupdate
pose0_config: [true, true, false, false, false, true,
               false, false, false, false, false, false,
               false, false, false]
pose0_differential: false
pose0_relative: false

# Optional: IMU (jeśli masz)
# imu0: imu/data
# imu0_config: [false, false, false, true, true, true,
#               false, false, false, false, false, false,
#               false, false, false]
# imu0_differential: false
# imu0_remove_gravitational_acceleration: true

# Publikacja
publish_tf: true
map_frame: map
odom_frame: odom
base_link_frame: base_footprint
world_frame: odom